version: "3.3"
services:
  orchestrator:
    image: tripplanner.orchestrator
    build:
      dockerfile: ./TripPlanner.Orchestrator/Dockerfile
    ports:
      - "5001:80"
  hostel:
    image: tripplanner.hostel
    build:
      dockerfile: ./TripPlanner.Hostel/Dockerfile
    ports:
      - "5002:80"
  flight:
    image: tripplanner.flight
    build:
      dockerfile: ./TripPlanner.Flight/Dockerfile
    ports:
      - "5003:80"